// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1LGz7hBhD8PJ5EgCqciQE0T_mom5WbVw',
    appId: '1:973082073526:web:7140d8ac61423da885c917',
    messagingSenderId: '973082073526',
    projectId: 'chatinc-88717',
    authDomain: 'chatinc-88717.firebaseapp.com',
    storageBucket: 'chatinc-88717.appspot.com',
    measurementId: 'G-ZEBTG2V55J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBF-r_t4_PcW8izXQiMQOP736OJCDdbYjk',
    appId: '1:973082073526:android:c58c6c4e76ea5e3985c917',
    messagingSenderId: '973082073526',
    projectId: 'chatinc-88717',
    storageBucket: 'chatinc-88717.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKQtC6X7CeiW3jurzsER4QRsL861xq_1k',
    appId: '1:973082073526:ios:142a7249d10fbbe485c917',
    messagingSenderId: '973082073526',
    projectId: 'chatinc-88717',
    storageBucket: 'chatinc-88717.appspot.com',
    iosBundleId: 'com.example.chatinc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKQtC6X7CeiW3jurzsER4QRsL861xq_1k',
    appId: '1:973082073526:ios:142a7249d10fbbe485c917',
    messagingSenderId: '973082073526',
    projectId: 'chatinc-88717',
    storageBucket: 'chatinc-88717.appspot.com',
    iosBundleId: 'com.example.chatinc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1LGz7hBhD8PJ5EgCqciQE0T_mom5WbVw',
    appId: '1:973082073526:web:6f1e1338aec81ca385c917',
    messagingSenderId: '973082073526',
    projectId: 'chatinc-88717',
    authDomain: 'chatinc-88717.firebaseapp.com',
    storageBucket: 'chatinc-88717.appspot.com',
    measurementId: 'G-KTP9L4DMJZ',
  );
}
